name: ci
on:
  push:
    branches: [ main, stable ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main, stable ]
    paths-ignore:
      - docs/**
      - README.md
      - CHANGELOG.md
jobs:
  build_and_upload_macos:
    name: Build for MacOS-12
    runs-on: macos-12
    strategy:
      matrix:
        build: [ Release, Debug ]
    steps:
      - uses: actions/checkout@v2
      - name: Select Xcode 13.4
        run: sudo xcode-select --switch /Applications/Xcode_13.4.app
      - name: Install conan and build dependencies
        run: |
          pip3 install -U pip
          pip3 install conan
          brew install gcc@11
      - name: Get list of dependencies
        run: curl -o conanfile.txt https://raw.githubusercontent.com/reduct-storage/reduct-storage/main/conanfile.txt
      - name: Build and install
        run: conan install . --build=* -s build_type=${{ matrix.build }}
      - name: Register in Conan Repo
        run: |
          conan remote add reduct https://reductstorage.jfrog.io/artifactory/api/conan/default-conan-local
          conan user -p ${{ secrets.CONAN_TOKEN }} -r reduct ${{ secrets.CONAN_USER }}
      - name: Upload packages
        run: cat conanfile.txt  | grep -e "/" | xargs -n 1 conan upload -c -r reduct --all


  build_and_upload_windows:
    name: Build for Windows
    runs-on: windows-2019
    strategy:
      matrix:
        build: [ Release, Debug ]
    steps:
      - uses: actions/checkout@v2
      - name: Update windows SDK
        uses: fbactions/setup-winsdk@v1
        with:
          winsdk-build-version: 19041
      - name: Install conan and build dependencies
        run: |
          pip3 install -U pip
          pip3 install conan
      - name: Get list of dependencies
        shell: bash
        run: curl -o conanfile.txt https://raw.githubusercontent.com/reduct-storage/reduct-storage/main/conanfile.txt
      - name: Build and install
        run: conan install . --build=* -s build_type=${{ matrix.build }}
      - name: Register in Conan Repo
        run: |
          conan remote add reduct https://reductstorage.jfrog.io/artifactory/api/conan/default-conan-local
          conan user -p ${{ secrets.CONAN_TOKEN }} -r reduct ${{ secrets.CONAN_USER }}
      - name: Upload packages
        shell: bash
        run: cat conanfile.txt  | grep -e "/" | xargs -n 1 conan upload -c -r reduct --all